### ISSUE TITLE
Does not work with OwnCloud 9

### ISSUE THREAD

**Issue by suterma** [rafaelgou/owncloud-bootswatch-themes#4]
While I really like the idea of having cool themes, these seem not to work with ownCloud 9. I tried 2 of them with the Stylish Firefox plugin and they looked awkward.

The ones I tried are "lumen" and "spacelab".

However, I must say, I appreciate your effort so far.

**Comment by brumle80** [comment]
second this, would love for it to be working again, wish I could fix it myself, but alas...

**Comment by nimonian** [comment]
The themes themselves do have an effect, I have had success in installing the yeti theme, but I'm having issues with the layout. Most notably, the + button to add a new file in the menu bar appears floating on top of the content just below the menu. I am too inept to approach this myself but I hope the feedback helps - thanks also for your work.

**Comment by rafaelgou** [comment]
Hey, guys,

I'm not using Owncloud for more than an year, and not in touch with version 9.0.

Sorry for that.

**Comment by Webdeern** [comment]
this is really bad, the support for themes for Owncloud is sooo pooor...

one of the negative points for this systems.

Rafaelgou, please note at the github page that this is outdated for owncloud  9, you would save a lot of stress, anger and time for all of us who try to get this working...

cheers, Connie

**Comment by rafaelgou** [comment]
Good call, @Webdeern .

Just did that: https://github.com/rafaelgou/owncloud-bootswatch-themes/commit/cd6a5e33bf1629361ffcffb72d573ccd505bfac1
